// Writes loorel.gen.ts: endpoint name -> { api, model }. @loorel/client reads it, so the
// caller side knows every endpoint without depending on @loorel/define.
// Run from the project root (the directory with loorel.config.ts):
//
//   node packages/define/src/types.ts [--check]
//
// --check writes nothing and exits 1 when loorel.gen.ts is out of date.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ConfigError, type LoadedEndpoint, loadEndpoints } from "./config.ts";

const GEN_FILE = "loorel.gen.ts";

const key = (name: string) => (/^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name));

/** The contents of loorel.gen.ts. Formatted as `vp check` leaves it. */
export function renderTypes(endpoints: LoadedEndpoint[]): string {
  const entries = endpoints.map((e) =>
    [
      `  ${key(e.name)}: {`,
      `    api: ${JSON.stringify(e.api)},`,
      `    model: ${JSON.stringify(e.model)},`,
      "  },",
    ].join("\n"),
  );
  const body = entries.length > 0 ? `{\n${entries.join("\n")}\n}` : "{}";
  return [
    "// Generated by `pnpm types` from endpoints/*/endpoint.config.ts. Do not edit.",
    "// Pass `endpoints` to createLoorelClient from @loorel/client.",
    `export const endpoints = ${body} as const;`,
    "",
    "export type Endpoints = typeof endpoints;",
    "",
  ].join("\n");
}

/** Returns the process exit code. */
export async function types({
  argv,
  root,
  log = console.log,
}: {
  argv: string[];
  root: string;
  log?: (line: string) => void;
}): Promise<number> {
  const check = argv.includes("--check");
  if (argv.some((a) => a !== "--check")) {
    log("usage: types.ts [--check]");
    return 2;
  }
  let text: string;
  try {
    text = renderTypes(await loadEndpoints(root));
  } catch (e) {
    if (!(e instanceof ConfigError)) throw e;
    log(`error: ${e.message}`);
    return 1;
  }
  const file = path.join(root, GEN_FILE);
  if (check) {
    const current = await readFile(file, "utf8").catch(() => null);
    if (current === text) return 0;
    log(`error: ${GEN_FILE} is out of date; run pnpm types`);
    return 1;
  }
  await writeFile(file, text);
  log(`wrote ${GEN_FILE}`);
  return 0;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  process.exitCode = await types({ argv: process.argv.slice(2), root: process.cwd() });
}
