// Generated by `pnpm types` from endpoints/*/endpoint.config.ts. Do not edit.
// Pass `endpoints` to createLoorelClient from @loorel/client.
export const endpoints = {
  "qwen3-8b": {
    api: "openai",
    model: "qwen3-8b",
  },
} as const;

export type Endpoints = typeof endpoints;
